<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{9aae132b-922d-4c22-b319-ce77ea2693a9}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	Grap_PositionAxis1 AT%QD100 :PositionAxis;
	Grap_PositionAxis1_Status AT%ID100:PositionAxis_Status;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>